# This rule is not used by the project app-cleanup-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the cleanup.io.app-cleanup.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: app-cleanup-operator
    app.kubernetes.io/managed-by: kustomize
  name: appcleanup-editor-role
rules:
- apiGroups:
  - cleanup.io.app-cleanup.io
  resources:
  - appcleanups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cleanup.io.app-cleanup.io
  resources:
  - appcleanups/status
  verbs:
  - get
