# This rule is not used by the project app-cleanup-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to argo.app-cleanup.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: app-cleanup-operator
    app.kubernetes.io/managed-by: kustomize
  name: namespace-viewer-role
rules:
- apiGroups:
  - argo.app-cleanup.io
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argo.app-cleanup.io
  resources:
  - namespaces/status
  verbs:
  - get
