---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - delete
  - get
  - list
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applications/finalizers
  verbs:
  - update
- apiGroups:
  - cleanup.io.app-cleanup.io
  resources:
  - appcleanups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cleanup.io.app-cleanup.io
  resources:
  - appcleanups/finalizers
  verbs:
  - update
- apiGroups:
  - cleanup.io.app-cleanup.io
  resources:
  - appcleanups/status
  verbs:
  - get
  - patch
  - update
