---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - argo.app-cleanup.io
  resources:
  - deployments
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argo.app-cleanup.io
  resources:
  - deployments/finalizers
  - namespaces/finalizers
  verbs:
  - update
- apiGroups:
  - argo.app-cleanup.io
  resources:
  - deployments/status
  - namespaces/status
  verbs:
  - get
  - patch
  - update
